---
- hosts: ios
  gather_facts: no
  tasks:
   - name: qos VOIP_ACL
     ios_config:
       lines:
       - remark RTP VOIP and TELEPRESENCE
       - permit udp any any range 16384 32767 dscp ef
       parents: ip access-list extended VOIP_ACL

   - name: qos SIGNALLING_ACL
     ios_config:
       lines:
       - remark Call Signaling/Jabber_CS3
       - remark SCCP
       - permit tcp any any range 2000 2002
       - remark SIP
       - permit tcp any any range 5060 5061
       - permit udp any any range 5060 5061
       parents: ip access-list extended SIGNALLING_ACL

   - name: qos class-map VOIP
     ios_config:
       lines:
       - match access-group name VOIP_ACL
       parents: class-map match-any VOIP
